# @package _global_
defaults:
  - /core/base@
  - /default_finetune_seg@
  - /model/resenc_unet_b@model
  - _self_

task: SEG007_CEREBRUM-7T
rootcfg: datapaper
stemcfg: default_train

training:
  epochs: 150
  warmup_epochs: 10
  decoder_warmup_epochs: 10
  batch_size: 2

data: # dataset is 142 sessions
  train_split: BIDSsplit_15_35_50
  test_split: BIDSTEST_15_35_50
