# @package _global_
defaults:
  - /core/base@
  - /default_train_seg@
  - /model/resenc_unet_b@model
  - _self_

task: SEG008_WMH
rootcfg: datapaper
stemcfg: default_train

training:
  epochs: 150
  warmup_epochs: 10
  decoder_warmup_epochs: 10
  batch_size: 2

data: # dataset is 170 sessions
  train_split: split_12_38_50
  test_split: TEST_12_38_50
