# @package _global_
defaults:
  - /core/base@
  - /default_train_seg@
  - /hardware/cpu@hardware
  - /model/unet_tiny@model
  - _self_

task: 
root: base
stem: debug

model:
  dimensions: 3D

training:
  patch_size: [32, 32, 32]
  batch_size: 2
  train_batches_per_epoch_per_device: 10
  val_batches_per_epoch_per_device: 5
  epochs: 5

logger:
  progress_bar: True
  profile: False
  wandb_log_model: False
  wandb_logging: False
  mlflow_logging: False
  log_every_n_steps: 1
  log_images_every_n_epoch: 999999